apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-sql-proxy
  namespace: airflow
  annotations:
    iam.gke.io/gcp-service-account: sa-airflow-dev@dtp-ref-dev.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sql-proxy
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-sql-proxy
  template:
    metadata:
      labels:
        app: cloud-sql-proxy
    spec:
      serviceAccountName: cloud-sql-proxy
      containers:
        - name: proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
          args:
            - "--structured-logs"
            - "--address=0.0.0.0"
            - "--port=5432"
            - "dtp-ref-dev:europe-central2:airflow-meta-dev"
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: postgres
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-sql-proxy
  namespace: airflow
spec:
  type: ClusterIP
  selector:
    app: cloud-sql-proxy
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres