name: finance
version: "1.0.0"
config-version: 2
profile: finance

model-paths: ["models"]
target-path: "target"

vars:
  gcp_project: "{{ env_var('GCP_PROJECT') }}"
  dtp_env: "{{ env_var('DTP_ENV', 'dev') }}"

models:
  finance:
    +persist_docs: { relation: true, columns: true }
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +partition_by: { field: revenue_date, data_type: date, granularity: day }
      +schema: mart
      +labels: { domain: finance, layer: mart }
